server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/planitache

# JWT Configuration
# Ce secret est encodé en Base64 et fait plus de 256 bits pour satisfaire l'algorithme HS256/HS512
jwt.secret=dGhpcy1pcy1hLXZlcnktc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLXBsYW5pdGFjaGUtYXBwbGljYXRpb24tc3ByaW5nLWJvb3Q=
# Expiration de 7 jours en millisecondes (7 * 24 * 60 * 60 * 1000)
jwt.expiration=604800000
